<div class="row">
    <div class="col s5 m5 l6 push-s1 push-m1" style="margin-top: -30px">
        <h5 class="teal-text">
            Управление языками
        </h5>
    </div>
    <div class="col s6 m6 l6 right-align" style="margin-top: -26px">
        <a class="btn-floating btn-large waves-effect waves-light red modal-trigger add-language-modal" href="#add-news-modal"><i class="material-icons">add</i></a>
    </div>
</div>
<div class="row">

    <div class="col s12 m 12 l12">
        <table class="highlight">
            <thead>
            <tr>
                <th data-field="language">Язык</th>
                <th data-field="code">Код</th>
                <th data-field="visible">Активный</th>
                <th data-field="actions">Управление</th>
            </tr>
            </thead>
            <tbody>
                <?php foreach ($languages as $lang) {?>
                    <tr>
                        <td id="name">
                            <?= $lang->name?>
                        </td>
                        <td id="code">
                            <?= $lang->code?>
                        </td>
                        <td id="visible">
                            <?= $lang->visible ?>
                        </td>
                        <?php if ($lang->code != 'all') { ?>
                            <td>
                                <?= $this->tag->linkTo(['languages/edit/', '<i class="material-icons">mode_edit</i>', 'class' => 'btn-floating edit-language-btn', 'title' => 'Редактировать', 'id' => "$lang->id"]) ?>
                                <?= $this->tag->linkTo(['languages/delete/'.$lang->id, '<i class="material-icons">delete</i>', 'class' => 'btn-floating red lighten-1 delete-language-btn', 'id' => $lang->id, 'title' => 'Удалить']) ?>
                            </td>
                        <?php } else { ?>
                            <td>

                            </td>
                        <?php } ?>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>

</div>

<div id="add-language-modal" class="modal">
    <div class="modal-content">
        <div class="row">
            <?=  Phalcon\Tag::form(array("languages/add", "method" => "post", 'class' => 'col s12 m12 l12', 'id' => 'language-add-form')); ?>
                <input type="hidden" id="lstat" value="" name="lstat">
                <div class="row">
                    <div class="input-field col s12 m12 l12">
                        <input placeholder="Язык" id="language_name" name="name" type="text" class="validate">
                        <label for="language_name">Язык</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m12 l12">
                        <input placeholder="Код" id="language_code" name="code" type="text" class="validate">
                        <label for="language_code">Код языка</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <select name="visible" id="language_visible">
                            <option value="yes">Да</option>
                            <option value="no">Нет</option>
                        </select>
                        <label>Включить</label>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12 m12 l12">
                        <?= Phalcon\Tag::submitButton(['Save', 'class' => 'btn waves-effect waves-light submit-language-add' ]) ?>
                    </div>
                </div>
            <?= \Phalcon\Tag::endForm(); ?>
        </div>
    </div>
</div>