<div class="row">
    <div class="col s6 m6 l6" style="margin-top: -30px">
        <h5 class="teal-text">
            Добавить новую страницу
        </h5>
    </div>
</div>
<div class="row">
    <form class="col s12 add-news-form" action="/admin/pages/add" method="post">
        <input type="hidden" id="pstat" value="" name="pstat">
        <div class="row">
            <div class="input-field col s12">
                <input placeholder="Заголовок" id="title" name="title" type="text" class="validate <?= (isset($errors['title'])) ? ' invalid' : '' ?>">
                <label for="title" data-error="<?= (isset($errors['title'])) ? $errors['title'] : '' ?>">Название</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <textarea  value="Полное описание" type="text" id="page-description" name="content" class="materialize-textarea validate <?= (isset($errors['content'])) ? ' invalid' : '' ?>"> </textarea>
                <label for="page-description" data-error="<?= (isset($errors['content'])) ? $errors['content'] : '' ?>" data-error="" style="padding-bottom: 10px">Содержание страницы</label>
            </div>
        </div>

        <div class="row">
            <div class="col s12 input-field">
                <ul class="collapsible" data-collapsible="accordion" style="width: 640px !important; ">
                    <li>
                        <div class="collapsible-header">
                            <i class="material-icons">settings</i>SEO Настройки
                        </div>
                        <div class="collapsible-body">
                            <div class="row" style="margin-top: 10px">
                                <div class="input-field col s12">
                                    <input placeholder="SEO Заголовок" id="page-seo-title" name="seoTitle" type="text" class="validate">
                                    <label for="news-seo-title">SEO Заголовок</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12">
                                    <input placeholder="SEO ключевые слова" id="page-seo-keywords" name="seoKeywords" type="text" class="validate">
                                    <label for="news-seo-keywords">SEO ключевые слова</label>
                                </div>
                            </div>
                            <div class="row">
                                <div class="input-field col s12">
                                    <textarea  value="SEO описание" type="text" name="seoDescription" id="page-seo-description" class="materialize-textarea validate" length="160"> </textarea>
                                    <label for="news-seo-description">SEO описание</label>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>

        <div class="row">
            <div class="col s12 input-field" style="width:660px !important;">
                <select name="languageId" id="language-id">
                    <?php foreach ($languages AS $language) { ?>
                        <?php  $selected = ($language->code == 'ru') ? ' selected ' : '' ?>
                        <option value="<?php echo $language->id ?>" <?= $selected ?> > <?php echo $language->name ?></option>
                    <? } ?>
                </select>
                <label>Язык новости</label>
            </div>
        </div>

        <div class="row">
            <div class="col s12 input-field center" style="margin-top: 30px;">
                <button class="btn waves-effect waves-light submit-news" type="submit" name="action">
                    Сохранить<i class="material-icons right">send</i>
                </button>
            </div>
        </div>
    </form>
</div>