<div class="row">
    <div class="col s5 m5 l6 push-s1 push-m1" style="margin-top: -30px">
        <h5 class="teal-text">
            Страницы
        </h5>
    </div>
    <div class="col s6 m6 l6 right-align" style="margin-top: -26px">
        <a class="btn-floating btn-large waves-effect waves-light red modal-trigger add-page-modal" href="/admin/pages/add"><i class="material-icons">add</i></a>
    </div>
</div>
<div class="row">
    <div class="col s12 m 12 l12">
        <table class="highlight">
            <thead>
            <tr>
                <th data-field="language">Заголовок</th>
                <th data-field="code">Дата добавления</th>
                <th data-field="visible">Язык</th>
                <th data-field="actions" class="center-align">Управление</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($pages as $page) {?>
                <tr id="page-<?= $page->id ?>" class="sortable-pages">
                    <td id="name">
                        <?= $page->title?>
                    </td>
                    <td id="code">
                        <?= $page->dateAdded?>
                    </td>
                    <td id="visible">
                        <?= $langsMap[$page->languageId] ?>
                    </td>
                    <td>
                        <div class="center-align">
                            <?= $this->tag->linkTo(['#', '<i class="material-icons">delete</i>', 'class' => 'btn-floating red lighten-1 delete-page-btn', 'id' => $page->id, 'title' => 'Удалить']) ?>

                            <?= $this->tag->linkTo(['/admin/pages/edit/'. $page->id, '<i class="material-icons">mode_edit</i>', 'class' => 'btn-floating edit-page-btn', 'title' => 'Редактировать', 'id' => "$page->id"]) ?>
                        </div>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>
