<?
use library\Widgets\FooterContactWidget;
use library\Widgets\FooterFeedbackWidget;
?>
<footer class="page-footer white" style="background-color: #f9f9f9;">
    <div class="container">
        <div class="row">
            <div class="col s12 m6 l6 ">
                <?= (new FooterContactWidget())->getWidget(); ?>
            </div>
            <div class="col s12 m6 l6" id="feedback-message">
                <?= (new FooterFeedbackWidget())->getWidget()?>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            Made by <a class="orange-text text-lighten-3" href="https://www.facebook.com/Maris.Vigulis">Maris Vigulis</a>
        </div>
    </div>
</footer>