<?php
    use app\models\Contacts;
?>

<h5 class="black-text">"De Lana Auto"</h5>
<p class="black-text text-lighten-4">

    <?php if ($hasContactsData) { ?>

        <?php if(!empty(Contacts::getAddress() )) { ?>
            <?php  $address = Contacts::getAddress(); ?>
            <?= $this->translate->_('Наш адрес') ?>:
            <?php if (!is_array($address)) {
                echo $address;
            } else {
                echo implode(', ', $address);
            }?> <br> <br>
        <?php } ?>

        <?php if(!empty(Contacts::getPhone() )) { ?>
            <?php  $phones = Contacts::getPhone(); ?>
            <?= $this->translate->_('Телефон')?> :
            <?php if (!is_array($phones)) {
                echo $phones;
            } else {
               echo implode(', ', $phones);
            }?> <br> <br>
        <?php } ?>

        <?php if(!empty(Contacts::getEmail() )) { ?>
            <?php  $emails = Contacts::getEmail(); ?>
            <?= $this->translate->_('Email') ?> :
            <?php if (!is_array($emails)) {
                echo $emails;
            } else {
                echo implode(', ', $emails);
            }?> <br> <br>
        <?php } ?>

        <?php if(!empty(Contacts::getSkype() )) { ?>
            <?php  $skype = Contacts::getSkype(); ?>
            <?= $this->translate->_('Skype') ?> :
            <?php if (!is_array($skype)) {
                echo $skype;
            } else {
                echo implode(', ', $skype);
            }?> <br> <br>
        <?php } ?>

    <?php } ?>
</p>