<?
use library\Widgets\FooterContactWidget;
use library\Widgets\FooterFeedbackWidget;
?>
<footer class="page-footer light-blue lighten-2">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <?= (new FooterContactWidget())->getWidget(); ?>
            </div>
            <div class="col l3 s12" id="feedback-message">
                <?= (new FooterFeedbackWidget())->getWidget()?>
            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Connect</h5>
                <ul>
                    <li><a class="white-text" href="#!">Link 1</a></li>
                    <li><a class="white-text" href="#!">Link 2</a></li>
                    <li><a class="white-text" href="#!">Link 3</a></li>
                    <li><a class="white-text" href="#!">Link 4</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            Made by <a class="orange-text text-lighten-3" href="https://www.facebook.com/Maris.Vigulis">Maris Vigulis</a>
        </div>
    </div>
</footer>