<?php
    use library\Widgets\FooterContactWidget;
    use library\Widgets\FooterFeedbackWidget;
?>
<div class="divider"></div>
<footer class="page-footer white" style="background-color: #f9f9f9;">
    <div class="row" style="margin-left: 20px">
        <div class="col s12 m4 l3">
            <?= (new FooterContactWidget())->getWidget(); ?>
        </div>
        <div class="col sm12 m4 l4" id="footer-contacts-form">
            <form class="col s12 m12 l12" method="post" action="/<?= LOCALE_CODE ?>/contacts/support"  onsubmit="return checkform(this);">
                <div class="col s12 m12 l12 ">
                    <h5 class="left-align" >
                        <?= $this->translate->_('Задайте нам вопрос') ?>
                    </h5>
                </div>
                <div class="row">
                    <div class="input-field col s12 m12 l11">
                        <input id="firstname" type="text" name="firstname" class="validate <?= (isset($errors['firstname'])) ? ' invalid' : '' ?>">
                        <label for="firstname" data-error="<?= $errors['firstname'] ?? '' ?>"><?= $this->translate->_('Имя') ?></label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m12 l11">
                        <input id="email" type="email" name="email" class="validate <?= (isset($errors['email'])) ? ' invalid' : '' ?>">
                        <label for="email"  data-error="<?= $errors['email'] ?? '' ?>"><?= $this->translate->_('Email') ?></label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m12 l12">
                        <textarea id="content" name="content" class="materialize-textarea validate <?= (isset($errors['content'])) ? ' invalid' : '' ?>"></textarea>
                        <label for="content"  data-error="<?= $errors['content'] ?? '' ?>"><?= $this->translate->_('Сообщение') ?></label>
                    </div>
                </div>
                <div class="row">
                    <div class="col s7 m7 l7 input-field">
                        <button class="btn waves-effect waves-light light-blue" type="submit">
                            <?= $this->translate->_('Отправить') ?><i class="material-icons right">send</i>
                        </button>
                    </div>
                    <div class="col s5 m5 l5">
                        <div class="capbox">
                            <div id="CaptchaDiv"></div>
                            <div class="capbox-inner">
                                <?= $this->translate->_('Введите число выше') ?>:<br>

                                <input type="hidden" id="txtCaptcha">
                                <input type="text" name="CaptchaInput" id="CaptchaInput" size="12"><br>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="col s12 m4 l4" >
            <?= (new FooterFeedbackWidget())->getWidget()?>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            <a class="red-text text-lighten-1" href="http://maris-dev.tech/">Maris Vigulis</a>
        </div>
    </div>
</footer>