<?php
    $langsCount = count($languages);
?>
<div class="row">
    <div class="col s5 m5 l6 push-s1 push-m1" style="margin-top: -30px">
        <h5 class="teal-text">
            Перевод текстов
        </h5>
    </div>
</div>
<div class="divider"></div>

<div class="row">
    <table class="highlight">
        <thead>
            <th>
                Текст
            </th>
            <?php foreach ($languages as $id    =>  $language) { ?>
                <th> <?= $language; ?></th>
            <?php } ?>
        </thead>

        <tbody>
            <?php foreach ($keywords as $id =>  $keyword) { ?>
                <tr>
                    <td>
                        <?= $keyword['keyword'] ?>
                    </td>
                    <?php foreach ($translates as $languageTranslate    =>  $translate) { ?>
                       <td data-keyword-id="<?= $keyword['id'] ?>" data-language-id="<?= $languageTranslate ?>" contenteditable>
                           <?= empty($translate[$keyword['keyword']]) ? "&mdash;" : $translate[$keyword['keyword']] ?>
                       </td>
                    <?php } ?>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>