<?
 use library\Utils\Slug;
?>
<div class="row">
    <div class="col s5 m5 l5 push-s1 push-m1 push-l1" style="margin-top: -30px">
        <h5 class="teal-text">
            Последние добавленные новости
        </h5>
    </div>
    <div class="col s6 m6 l6 right-align" style="margin-top: -26px">
        <a class="btn-floating btn-large waves-effect waves-light red modal-trigger add-news-modal" href="#add-news-modal"><i class="material-icons">add</i></a>
    </div>
</div>
<div class="divider"></div>
<div class="row">
    <?php if ($news->total_items > 0) { ?>
        <?php foreach ($news->items as $new) { ?>
            <div class="col s6 l4 m3">
                <div class="card hoverable small">
                    <div class="card-image">
                        <img src="<?= ($new->image != null) ? $new->image : '/img/noimage.png' ?>">
                        <span class="card-title"><?= mb_substr($new->title, 0 ,20) ?>...</span>
                    </div>
                    <div class="card-content">
                        <p>
                            <?= mb_substr($new->shortDescription, 0 ,20) ?>
                        </p>
                    </div>
                    <div class="card-action" style="padding-bottom: 0px">
                        <div class="row">
                            <div class="col s12 m12 l12">
                                <?= $this->tag->linkTo([$new->getLink(), mb_substr($new->title, 0 ,20).'...', 'title' => "$new->title"]) . '<br><br>' ?>
                            </div>
                            <div class="col s12 m12 l12">
                                <div class="left">
                                    <a href="#" class="btn-floating edit-new-btn" id="<?= $new->id ?>" title="Редактировать"><i class="material-icons">mode_edit</i></a>
                                    <a href="#" class="btn-floating red lighten-1 delete-new-btn" title="Удалить" id="<?= $new->id?>"><i class="material-icons">delete</i></a>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        <?php } ?>
    <?php } else { ?>
        <div class="col s12">
            <h5 class="center-align">Пока что новостей нет</h5>
        </div>
    <?php } ?>
</div>

<?php if ($news->total_items  > 0) { ?>

<ul class="pagination">
    <li class="<?= ($news->before  < 1) ? 'disabled' : 'waves-effect' ?>">
        <?= $this->tag->linkTo(['admin/news/page/'.$news->before, '<i class="material-icons">chevron_left</i>']) ?>
    </li>
    <? if($news->current != 1) { ?>
        <li class="waves-effect">
            <?= $this->tag->linkTo(['admin/news/page/'.$news->before, $news->before]) ?>
        </li>
    <? }?>
    <li class="waves-effect active">
        <?= $this->tag->linkTo(['admin/news/page/'.$news->current, $news->current]) ?>
    </li>
    <? if($news->current != $news->total_pages) { ?>
        <li class="<?= ($news->next  > $news->total_pages) ? 'disabled' : 'waves-effect' ?>">
            <?= $this->tag->linkTo(['admin/news/page/'.$news->next, $news->next]) ?>
        </li>
    <? } ?>
    <li class="waves-effect">
        <?= $this->tag->linkTo(['admin/news/page/'.$news->last, '<i class="material-icons">chevron_right</i>']) ?>
    </li>
</ul>

<?php } ?>

<div id="add-news-modal" class="modal">
    <div class="modal-content">
        <div class="row">
            <form class="col s12 add-news-form">
                <input type="hidden" id="nstat" value="" name="nstat">
                <div class="row">
                    <div class="input-field col s12">
                        <input placeholder="Заголовок" id="title" name="title" type="text" class="validate">
                        <label for="news-title">Заголовок</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <textarea  value="Краткое описание" type="text" id="news-short-description" name="shortDescription" class="materialize-textarea validate" length="200"> </textarea>
                        <label for="news-short-description">Краткое описание</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <textarea  value="Полное описание" type="text" id="news-full-description" name="fullDescription" class="materialize-textarea classy-editor validate"> </textarea>
                        <label for="news-full-description" style="padding-bottom: 10px">Полное описание</label>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12 file-field input-field news-image">
                        <div class="btn">
                            <span>Изображение</span>
                            <input type="file" id="news-image">
                            <input type="hidden" value="" id="news-image-path">
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" name="image" type="text" placeholder="Выберите изображение">
                        </div>
                    </div>
                    <div class="col s12">
                        <img class="materialboxed article-image" width="200" src="">
                    </div>
                </div>

                <div class="row">
                    <div class="col s12 input-field">
                        <select name="languageId" id="language-id">
                            <?php foreach ($languages AS $language) { ?>
                                <?php  $selected = ($language->code == 'ru') ? ' selected ' : '' ?>
                                <option value="<?php echo $language->id ?>" <?= $selected ?> > <?php echo $language->name ?></option>
                            <? } ?>
                        </select>
                        <label>Язык новости</label>
                    </div>
                </div>

                <div class="row">
                    <div class="col s12 input-field">
                        <ul class="collapsible" data-collapsible="accordion">
                            <li>
                                <div class="collapsible-header">
                                    <i class="material-icons">settings</i>SEO Настройки
                                </div>
                                <div class="collapsible-body" style="padding-left: 9px; padding-right: 9px">
                                    <div class="row" style="margin-top: 10px">
                                        <div class="input-field col s12">
                                            <input placeholder="SEO Заголовок" id="news-seo-title" name="seoTitle" type="text" class="validate">
                                            <label for="news-seo-title">SEO Заголовок</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <input placeholder="SEO ключевые слова" id="news-seo-keywords" name="seoKeywords" type="text" class="validate">
                                            <label for="news-seo-keywords">SEO ключевые слова</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <textarea  value="SEO описание" type="text" name="seoDescription" id="news-seo-description" class="materialize-textarea validate" length="160"> </textarea>
                                            <label for="news-seo-description">SEO описание</label>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12 input-field">
                        <div class="switch">
                            <label>
                                Скрыть
                                <input type="checkbox" name="published" id="published" checked>
                                <span class="lever"></span>
                                Опубликовать
                            </label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12 input-field center" style="margin-top: 30px;">
                        <button class="btn waves-effect waves-light submit-news" type="submit" name="action">
                            Сохранить<i class="material-icons right">send</i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>