<?php
use app\models\Teachers;
?>
<div class="row">
    <div class="col s12 m12 l8" style="margin-top: -30px">
        <h5 class="teal-text">
            Добавить новый опрос
        </h5>
    </div>
</div>

<div class="row">
    <form class="col s12 add-news-form" action="/admin/polls/add" method="post">

        <div class="row">
            <div class="input-field col s12">
                <input placeholder="Вопрос" id="question" name="question" type="text" class="validate <?= (isset($errors['question'])) ? ' invalid' : '' ?>">
                <label for="question" data-error="<?= (isset($errors['question'])) ? $errors['question'] : '' ?>">Вопрос</label>
            </div>
        </div>

        <div class="row">
            <div class="col s12 m6 l4 input-field">
                <select name="languageId" id="language-id">
                    <?php foreach ($languages AS $language) { ?>
                        <?php  $selected = ($language->code == 'all') ? ' selected ' : '' ?>
                        <option value="<?php echo $language->id ?>" <?= $selected ?>> <?php echo $language->name ?></option>
                    <? } ?>
                </select>
                <label>Язык опроса</label>
            </div>
            <div class="col s12 m6 l6 input-field">
                <div class="switch">
                    <label>
                        Скрыть
                        <input type="checkbox" name="active" id="active" checked>
                        <span class="lever"></span>
                        Опубликовать
                    </label>
                </div>
            </div>
        </div>

       <div id="answers-container">
           <div class="row">
               <div class="input-field col s9 m9 l9">
                   <input id="answers" name="answers[]" type="text" class="answers validate">
                   <label for="answers">Ответ - 1</label>
               </div>
               <div class="col s3 m3 l3 right-align">
                   <a class="btn-floating btn-large waves-effect waves-light red add-answer" href="#"><i class="material-icons">add</i></a>
               </div>
           </div>
           <div class="row">
               <div class="input-field col s9 m9 l9">
                   <input id="answers" name="answers[]" type="text" class="answers validate">
                   <label for="answers">Ответ - 2</label>
               </div>
           </div>
       </div>


        <div class="row">
            <div class="col s12 input-field center" style="margin-top: 30px;">
                <button class="btn waves-effect waves-light" type="submit">
                    Сохранить<i class="material-icons right">send</i>
                </button>
            </div>
        </div>
    </form>
</div>