<div class="row">
    <div class="col s5 m5 l8 push-s1 push-m1" style="margin-top: -30px">
        <h5 class="teal-text">
            Статистика опроса
        </h5>
    </div>
</div>
<div class="divider"></div>
<div class="row">
    <div class="col s12 m 12 l12">
        <canvas id="statistics-chart" width="100%" height="50%"></canvas>
    </div>
</div>
<script>
    var statistics = '<?= json_encode($statistics) ?>';

    initPollStatisticsChart(statistics);
</script>