<div class="row">
    <div class="col s3 l3 m3">
        <?php foreach ($news as $new) { ?>
            <div class="card hoverable small">
                <div class="card-image">
                    <img src="<?= $new->image ?>">
                    <span class="card-title"><?= $new->title ?></span>
                </div>
                <div class="card-content">
                    <p>
                        <?= $new->shortDescription ?>
                    </p>
                </div>
                <div class="card-action">
                    <?= $this->tag->linkTo('news/'.$new->id, $new->title) ?>
                    <?= $this->tag->linkTo('news/edit/'.$new->id, 'Labot', 'class => red-text') ?>
                </div>
            </div>
        <? } ?>
    </div>
    <div class="col s6 l6 m6">
        456
    </div>
</div>
