<div class="row">
    <div class="col s5 m5 l6 push-s1 push-m1" style="margin-top: -30px">
        <h5 class="teal-text">
            Обращения пользователей
        </h5>
    </div>
</div>
<div class="divider"></div>

<div class="row">
    <div class="col s12 m 12 l12">
        <table class="highlight responsive-table">
            <thead>
            <tr>
                <th>#</th>
                <th>Имя</th>
                <th>Сообщение</th>
                <th>Email</th>
                <th>Отправлено</th>
                <th>Управление</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($messages as $message) {?>
                <tr>
                    <td>
                        <?= $message->id ?>
                    </td>
                    <td>
                        <?= $message->firstname ?>
                    </td>
                    <td>
                        <?= $message->content ?>
                    </td>
                    <td>
                        <?= $message->email ?>
                    </td>
                    <td>
                        <?= $message->contactTime?>
                    </td>

                    <td>
                        <div class="center-align">
                            <?= $this->tag->linkTo(['#', '<i class="material-icons">delete</i>', 'class' => 'btn-floating red lighten-1 delete-feedback-btn', 'id' => $message->id, 'title' => 'Удалить']) ?>
                        </div>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>