
<? foreach ($news->items as $new) {?>
    <div class="section">
        <div class="row">
            <div class="news-image col s3 m3 l3">
                <img class="responsive-img" src="<?= $new->image ?>">
            </div>
            <div class="news-content col s9 m9 l9">
                <div class="row">
                    <div class="col s12 m12 l12">
                        <h3>
                            <?= $new->title ?>
                        </h3>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12 m12 l12 news-description">
                        <?= $new->shortDescription ?>
                    </div>
                </div>
                <div class="row news-sub-content">
                    <div class="col s6 m6 l6 news-read-button">
                        <?= $this->tag->linkTo([$new->getLink(), 'Читать всю новость', 'title' => "$new->title", 'class' => 'waves-effect light-blue lighten-1 btn']) . '<br><br>' ?>
                    </div>
                    <div class="col s6 m6 l6 news-date-added">
                        <?= $new->dateAdded ?>  <i class="material-icons ">schedule</i>
                    </div>
                </div>
            </div>
        </div>
    </div> <div class="divider"></div>
<? } ?>


<ul class="pagination">
    <li class="<?= ($news->before  <= 1) ? 'disabled' : 'waves-effect' ?>">
        <a href="/?page=<?= $news->before ?>"> <i class="material-icons">chevron_left</i> </a>
    </li>
    <li class="waves-effect active">
        <a href="/?page=<?= $news->current ?>"> <?= $news->current ?></a>
    </li>
    <? if($news->total_pages > 1) { ?>
        <li class="<?= ($news->next  >= $news->total_pages) ? 'disabled' : 'waves-effect' ?>">
            <a href="/?page=<?= $news->next ?>"> <?= $news->next ?></a>
        </li>
    <? } ?>
    <li class="waves-effect">
        <a href="/?page=<?= $news->last ?>"> <i class="material-icons">chevron_right</i> </a>
    </li>
</ul>




