<div class="row">
    <div class="col s12 m12 l12 center-align">
        <h5 class="left-align" id="category-title">
            <?= $new->title ?>
        </h5>
    </div>
</div>
<div class="row">
    <div class="news-image col s3 m3 l3">
        <?php if (!empty($new->image)) { ?>
            <img class="responsive-img" src="<?= $new->image ?>" alt="<?= $new->title ?>" title="<?= $new->title ?>">
        <?php } ?>
    </div>
    <div class="col s12 m12 l12">
        <?= $new->fullDescription ?>
    </div>
</div>