<div class="section no-pad-bot main-page-big-container">
    <div class="container">
        <br><br>
        <div class="row center">
            <a href="/contacts/course" id="app-for-course" class="btn-large waves-effect waves-light red">Подать заявку</a>
            <a href="/feedback" id="review-button" class="btn-large waves-effect waves-light light-blue">Оставить отзыв</a>
        </div>
        <br><br>
        <div class="row center ">
            <h5 class="header col s12 white-text lighten-2 left arrow_box">
                Запишись прямо сейчас и пройди лучший курс теоретического и практического обучения в автошколе De Lana Auto
            </h5>
        </div>
        <br><br>
    </div>
</div>
