<div class="row">
    <div class="col s12 m12 l12 center-align">
        <h5 id="category-title">Категории</h5>
    </div>
</div>
<ul class="collection categories-list">
   <?php if (count($categories)) { ?>
       <?php foreach ($categories as $category) { ?>
           <?= $this->tag->linkTo([$category['href'], $category['title'], "class" => "collection-item"]) ?>
       <?php } ?>
    <?php } else { ?>
        <h6 class="center">Категорий нет</h6>
    <?php } ?>
</ul>