<?php if ($poll) { ?>
<div class="row">
    <div class="col s12 m12 l12 center-align">
        <h5 id="category-title"><?= $this->translate->_('Наш опрос') ?></h5>
    </div>
</div>
<ul class="collection poll-container" data-poll-id="<?= $poll->id ?>" style="margin-bottom: 0px !important;">
    <p class="collection-item question-text" style="background-color: #f5f5f5;">
        <?= $poll->question ?>
    </p>
    <?php foreach (unserialize($poll->answers) as $index => $answer) { ?>
        <a class="collection-item poll-answer">
            <input name="anwers" type="radio" id="a_<?= $index ?>" data-answer="<?= $answer ?>" />
            <label for="a_<?= $index ?>"><?= $answer ?></label>
        </a>
    <?php } ?>
</ul>
<div style="width: 100% !important" class="hoverable">
    <a class="waves-effect waves-block waves-blue btn-flat center-align hoverable poll-answer-btn" style="background-color: #f5f5f5; width: 100%;">
         <?= $this->translate->_('Голосовать') ?>
    </a>
</div>
<?php } ?>