<?php
use app\models\Teachers;
?>
<div class="row">
    <div class="col s12 m12 l8 push-s1 push-m1 push-l1" style="margin-top: -30px">
        <h5 class="teal-text">
            Добавить нового преподователя/инструктора
        </h5>
    </div>
</div>
<hr>
<div class="row">
    <form class="col s12 add-news-form" action="/admin/instructors/add" method="post">
        <div class="row" style="margin-bottom: 50px">
            <div class="col s12 input-field">
                <p>
                    <input name="profStatus" type="radio" id="instructor" value="instructor" checked/>
                    <label for="instructor"> <?= Teachers::STATUS_INSTRUCTOR ?></label>
                </p>
                <p>
                    <input name="profStatus" type="radio" id="teacher" value="teacher"/>
                    <label for="teacher"><?= Teachers::STATUS_TEACHER ?></label>
                </p>
            </div>
        </div>

        <div class="row">
            <div class="input-field col s12">
                <input placeholder="Имя" id="firstname" name="firstname" type="text" class="validate <?= (isset($errors['firstname'])) ? ' invalid' : '' ?>">
                <label for="firstname" data-error="<?= (isset($errors['firstname'])) ? $errors['firstname'] : '' ?>">Имя</label>
            </div>
        </div>

        <div class="row">
            <div class="input-field col s12">
                <input placeholder="Фамилия" id="lastname" name="lastname" type="text" class="validate <?= (isset($errors['lastname'])) ? ' invalid' : '' ?>">
                <label for="lastname" data-error="<?= (isset($errors['lastname'])) ? $errors['lastname'] : '' ?>">Фамилия</label>
            </div>
        </div>

        <div class="row">
            <div class="input-field col s12">
                <input placeholder="Возраст" id="age" name="age" type="number" class="validate <?= (isset($errors['age'])) ? ' invalid' : '' ?>">
                <label for="age" data-error="<?= (isset($errors['age'])) ? $errors['age'] : '' ?>">Возраст</label>
            </div>
        </div>

        <div class="row">
            <div class="input-field col s12">
                <input placeholder="Машина" id="car" name="car" type="text" class="validate <?= (isset($errors['car'])) ? ' invalid' : '' ?>">
                <label for="car" data-error="<?= (isset($errors['car'])) ? $errors['car'] : '' ?>">Машина</label>
            </div>
        </div>

        <div class="row">
            <div class="input-field col s12">
                <input placeholder="Телефон" id="phone" name="phone" type="text" class="validate <?= (isset($errors['phone'])) ? ' invalid' : '' ?>">
                <label for="phone" data-error="<?= (isset($errors['phone'])) ? $errors['phone'] : '' ?>">Телефон</label>
            </div>
        </div>

        <div class="row">
            <div class="input-field col s12">
                <input placeholder="Email" id="email" name="email" type="text" class="validate <?= (isset($errors['email'])) ? ' invalid' : '' ?>">
                <label for="email" data-error="<?= (isset($errors['email'])) ? $errors['email'] : '' ?>">Email</label>
            </div>
        </div>

        <div class="row">
            <div class="col s12 file-field input-field teacher-photo">
                <div class="btn">
                    <span>Фотография</span>
                    <input type="file" id="teacher-photo">
                    <input type="hidden" name="image" value="" id="teacher-photo-path">
                </div>
                <div class="file-path-wrapper">
                    <input class="file-path validate" type="text" placeholder="Выберите фотографию">
                </div>
            </div>
            <div class="col s12">
                <img class="materialboxed article-image" width="200" src="">
            </div>
        </div>

        <div class="row">
            <div class="col s12 input-field">
                <ul class="collapsible" data-collapsible="accordion">
                    <li>
                        <div class="collapsible-header">
                            <i class="material-icons">settings</i>Дополнительная информация
                        </div>
                        <div class="collapsible-body">

                            <div class="row" style="margin-top: 15px">
                                <div class="input-field col s12">
                                    <textarea value="Информация" type="text" id="about" name="about" class="materialize-textarea teacher-about-text validate <?= (isset($errors['about'])) ? ' invalid' : '' ?>"> </textarea>
                                    <label for="about" data-error="<?= (isset($errors['about'])) ? $errors['about'] : '' ?>" data-error="" style="padding-bottom: 10px"></label>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>

        <div class="row">
            <div class="col s11 m11 l11 input-field">
                <select name="languageId" id="languageId">
                    <?php foreach ($languages AS $language) { ?>
                        <?php  $selected = ($language->id == $defaultSiteLanguage) ? ' selected ' : '' ?>
                        <option value="<?php echo $language->id ?>" <?= $selected ?> > <?php echo $language->name ?></option>
                    <? } ?>
                </select>
                <label>Язык</label>
            </div>
        </div>

        <div class="row">
            <div class="col s12 input-field center" style="margin-top: 30px;">
                <button class="btn waves-effect waves-light" type="submit">
                    Сохранить<i class="material-icons right">send</i>
                </button>
            </div>
        </div>
    </form>
</div>