<?php
use app\models\Teachers;
?>
<div class="row">
    <div class="col s5 m5 l6 push-s1 push-m1" style="margin-top: -30px">
        <h5 class="teal-text">
            Список инструкторов и преподователей
        </h5>
    </div>
    <div class="col s6 m6 l6 right-align" style="margin-top: -26px">
        <a class="btn-floating btn-large waves-effect waves-light red modal-trigger add-instructor-btn" href="/admin/instructors/add"><i class="material-icons">add</i></a>
    </div>
</div>

<div class="row">

    <div class="col s12 m 12 l12">
        <table class="highlight responsive-table">
            <thead>
            <tr>
                <th data-field="firstname">Имя</th>
                <th data-field="lastname">Фамилия</th>
                <th data-field="age">Возраст</th>
                <th data-field="car">Машина</th>
                <th data-field="image">Фотография</th>
                <th data-field="profStatus">Статус</th>
                <th data-field="phone">Телефон</th>
                <th data-fiel="about">Краткая информация</th>
                <th data-field="email">Email</th>
                <th>Управление</th>
            </tr>
            </thead>
            <tbody>
                <?php foreach ($teachers as $teacher) {?>
                    <tr>
                        <td id="firstname" class="left-align">
                            <?= $teacher->firstname?>
                        </td>
                        <td id="lastname" class="left-align">
                            <?= $teacher->lastname?>
                        </td>
                        <td id="age" class="left-align">
                            <?= $teacher->age ?>
                        </td>
                        <td id="car" class="left-align">
                            <?= $teacher->car ?>
                        </td>
                        <td id="photo" class="center-align">
                            <?php if ($teacher->image != null) { ?>
                                <a href="#" data-featherlight="<?= $teacher->image ?>">Показать</a>
                            <?php  } else { ?>
                                <p class="center-align">-</p>
                            <?php } ?>
                        </td>
                        <td id="profStatus" class="left-align">
                            <?= Teachers::getStatusTranslation($teacher->profStatus) ?>
                        </td>
                        <td id="phone" class="left-align">
                            <?= $teacher->phone ?>
                        </td>
                        <td id="about" class="center-align">
                            <?php if ($teacher->about != null) { ?>
                                <a href="#" data-featherlight='<div> <?= $teacher->about?>  </div>'>Показать</a>
                            <?php  } else { ?>
                                <p class="center-align">-</p>
                            <?php } ?>

                        </td>
                        <td id="email" class="left-align">
                            <?= $teacher->email ?>
                        </td>
                        <td>
                            <div class="left">
                                <?= $this->tag->linkTo(['/admin/instructors/edit/'.$teacher->id, '<i class="material-icons">mode_edit</i>', 'class' => 'btn-floating', 'title' => 'Редактировать', 'id' => "$teacher->id"]) ?>
                            </div>
                            <div class="right">
                                <?= $this->tag->linkTo(['#', '<i class="material-icons">delete</i>', 'class' => 'btn-floating red lighten-1 delete-teacher-btn', 'id' => $teacher->id, 'title' => 'Удалить']) ?>
                            </div>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>

</div>