<!-- START OF DROPDOWNS CONTENT -->
<ul id="header-menu-dropdown" class="dropdown-content">
    <li>
        <?= $this->tag->linkTo('/about/lecturers', 'Преподаватели' ) ?>
    </li>
    <li>
        <?= $this->tag->linkTo('/about/instructors', 'Инструкторы' ) ?>
    </li>
</ul>

<ul id="header-menu-category-dropdown" class="dropdown-content">
    <?php foreach ($categories as $category) { ?>
        <li>
            <?= $this->tag->linkTo($category['href'], $category['title'] ) ?>
        </li>
    <?php } ?>
</ul>

<ul id="header-menu-pages-dropdown" class="dropdown-content">
    <?php foreach ($pages as $page) { ?>
        <li>
            <?= $this->tag->linkTo($page['href'], $page['title'] ) ?>
        </li>
    <?php } ?>
</ul>


<ul id="header-menu-pages-dropdown" class="dropdown-content">
    <?php foreach ($pages as $page) { ?>
        <li>
            <?= $this->tag->linkTo($page['href'], $page['title'] ) ?>
        </li>
    <?php } ?>
</ul>

<ul id="top-header-menu-languages-dropdown" class="dropdown-content">
    <?php foreach ($languages as $language) { ?>
        <?php if ($language['name'] != '-- Все --') { ?>
            <li>
                <a href="<?= $language['href'] ?>">
                    <?= $language['name'] ?> <img src="<?= $language['img'] ?>">
                </a>
            </li>
        <?php } ?>
    <?php } ?>
</ul>
<!-- END OF DROPDOWNS CONTENT -->

<nav class="white" role="navigation" >
    <a href="#" data-activates="nav-mobile" style="color: grey;" class="button-collapse"><i class="material-icons">menu</i></a>
    <div class="nav-wrapper container">
        <a href="/" class="brand-logo center-align">
            <img class="responsive-img" id="logo-container" src="/img/logo2.jpg" >
        </a>

        <ul class="hide-on-med-and-down right">
            <li>
                <a href="/">Главная</a>
            </li>
            <li>
                <a class="dropdown-button" href="#" data-activates="header-menu-dropdown" data-beloworigin="true">
                    О нас<i class="material-icons right">arrow_drop_down</i>
                </a>
            </li>
            <li>
                <a class="dropdown-button" href="#" data-activates="header-menu-category-dropdown" data-beloworigin="true">
                    Категории<i class="material-icons right">arrow_drop_down</i>
                </a>
            </li>
            <li>
                <a class="dropdown-button" href="#" data-activates="header-menu-pages-dropdown" data-beloworigin="true">
                    Дополнительно<i class="material-icons right">arrow_drop_down</i>
                </a>
            </li>
            <li>
                <?= $this->tag->linkTo('contacts', 'Контакты')?>
            </li>
            <li class="right-align" id="language-selector-list-item">
                <a class="dropdown-button" id="language-selector" href="#" data-activates="top-header-menu-languages-dropdown" data-beloworigin="true" data-alignment="left">
                    <div class="valign-wrapper">
                        <img src="<?= $selectedLanguageData['img'] ?>" class="valign">   <i class="material-icons right">arrow_drop_down</i>
                    </div>
                </a>
            </li>
        </ul>


        <!-- Mobile navigation -->
        <ul id="nav-mobile" class="side-nav">
            <li>
                <a href="/">Главная</a>
            </li>

            <li>
                <a class="dropdown-button" href="#" data-activates="header-menu-dropdown-m" data-beloworigin="true">
                    О нас<i class="material-icons right">arrow_drop_down</i>
                </a>
            </li>

            <li>
                <a class="dropdown-button" href="#" data-activates="header-menu-category-dropdown-m" data-beloworigin="true">
                    Категории<i class="material-icons right">arrow_drop_down</i>
                </a>
            </li>

            <li>
                <a class="dropdown-button" href="#" data-activates="header-menu-pages-dropdown-m" data-beloworigin="true">
                    Дополнительно<i class="material-icons right">arrow_drop_down</i>
                </a>
            </li>

            <li>
                <a class="dropdown-button" id="language-selector" href="#" data-activates="top-header-menu-languages-dropdown-m" data-beloworigin="true" data-alignment="left">
                    <div class="valign-wrapper">
                        <img src="<?= $selectedLanguageData['img'] ?>" class="valign">   <i class="material-icons right">arrow_drop_down</i>
                    </div>
                </a>
            </li>

        </ul>
    </div>
</nav>

<!-- START OF MOBILE DROPDOWNS CONTENT -->
<ul id="header-menu-dropdown-m" class="dropdown-content">
    <li>
        <?= $this->tag->linkTo('/teachers', 'Преподаватели' ) ?>
    </li>
    <li>
        <?= $this->tag->linkTo('/instructors', 'Инструкторы' ) ?>
    </li>
</ul>

<ul id="header-menu-category-dropdown-m" class="dropdown-content">
    <?php foreach ($categories as $category) { ?>
        <li>
            <?= $this->tag->linkTo($category['href'], $category['title'] ) ?>
        </li>
    <?php } ?>
</ul>

<ul id="header-menu-pages-dropdown-m" class="dropdown-content">
    <?php foreach ($pages as $page) { ?>
        <li>
            <?= $this->tag->linkTo($page['href'], $page['title'] ) ?>
        </li>
    <?php } ?>
</ul>


<ul id="header-menu-pages-dropdown-m" class="dropdown-content">
    <?php foreach ($pages as $page) { ?>
        <li>
            <?= $this->tag->linkTo($page['href'], $page['title'] ) ?>
        </li>
    <?php } ?>
</ul>

<ul id="top-header-menu-languages-dropdown-m" class="dropdown-content">
    <?php foreach ($languages as $language) { ?>
        <?php if ($language['name'] != '-- Все --') { ?>
            <li>
                <a href="<?= $language['href'] ?>">
                    <?= $language['name'] ?> <img src="<?= $language['img'] ?>">
                </a>
            </li>
        <?php } ?>
    <?php } ?>
</ul>

<!-- END OF MOBILE DROPDOWNS CONTENT -->
