<div class="row">
    <div class="col s6 m6 l6" style="margin-top: -30px">
        <h5 class="teal-text">
            Категории
        </h5>
    </div>
    <div class="col s6 m6 l6 right-align" style="margin-top: -26px">
        <a class="btn-floating btn-large waves-effect waves-light red modal-trigger add-page-modal" href="/admin/categories/add"><i class="material-icons">add</i></a>
    </div>
</div>
<div class="row">
    <div class="col s12 m 12 l12">
        <table class="highlight responsive-table">
            <thead>
            <tr>
                <th data-field="language">Категория</th>
                <th data-field="code">Дата добавления</th>
                <th data-field="visible">Язык описания</th>
                <th data-field="actions" class="center-align">Управление</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($categories as $category) {?>
                <tr>
                    <td id="name">
                        <?= $category->title?>
                    </td>
                    <td id="code">
                        <?= $category->dateAdded?>
                    </td>
                    <td id="visible">
                        <?= $langsMap[$category->languageId] ?>
                    </td>
                    <td>
                        <div class="center-align">
                            <?= $this->tag->linkTo(['#', '<i class="material-icons">delete</i>', 'class' => 'waves-effect waves-light btn  red lighten-1 delete-category-btn', 'id' => $category->id, 'title' => 'Удалить']) ?>

                            <?= $this->tag->linkTo(['/admin/categories/edit/'. $category->id, '<i class="material-icons">mode_edit</i>', 'class' => 'waves-effect waves-light btn edit-category-btn', 'title' => 'Редактировать', 'id' => "$category->id"]) ?>
                        </div>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>
