<div class="row">
    <div class="col s12 m12 l12 center-align">
        <h5 class="left-align" id="category-title">
           <?= $lecturer->firstname . ' ' . $lecturer->lastname ?>
        </h5>
    </div>
</div>
<div class="row">
    <div class="col s12 m3 l3">
        <?php if (!empty($lecturer->image)) { ?>
            <div class="teacher-photo card-panel" data-featherlight="<?= $lecturer->image?>">
                <img class="responsive-img" src="<?= $lecturer->image ?>" alt="<?= $lecturer->firstname . ' ' . $lecturer->lastname ?>" title="<?= $lecturer->firstname . ' ' . $lecturer->lastname ?>">
            </div>
        <?php } ?>
    </div>
    <div class="col s12 m9 l9">
        <div class="card-panel">
            <span class="card-title">
              <b><?= $this->translate->_('Возраст') ?>:</b>
            </span>
            <?= $lecturer->age ?>
            <br><br><br>
            <span class="card-title">
                <b><?= $this->translate->_('Email') ?>:</b>
            </span>
            <?= $lecturer->email ?>
            <br><br><br>
            <?php if ($lecturer->about) { ?>
                <span class="card-title">
                    <b><?= $this->translate->_('Информация') ?>:</b>
                </span>
                <?= $lecturer->about ?>
            <?php } ?>
        </div>
    </div>
</div>