<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Панель администратора</title>

    <link rel="shortcut icon" href="images/favicon.png">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <?php $this->assets->outputCss() ?>
    <?php $this->assets->outputJs() ?>
</head>

<body>
    <header>
        <div class="container" style="margin-top: 5px; margin-left: 5px">
            <a href="#" data-activates="slide-out" class="button-collapse"><i class="material-icons">menu</i></a>
        </div>
        <ul id="slide-out" class="side-nav fixed">
            <li>
                <div class="userView">
                    <?= $this->tag->image(['img/admin-avatar.png', 'class' => 'circle responsive-img', 'id' => 'admin-avatar']) ?>
                    <p>
                        <span class="black-text name center-align">
                            Привет, <?= $admin->firstname ?> <a href="/admin/auth/logout"><i style="font-size: 20px" class="material-icons">exit_to_app</i></a>
                        </span>
                    </p>
                </div>
            </li>
            <li> <?= $this->tag->linkTo('admin/news', 'Новости <i class="left material-icons">speaker_notes</i>'); ?> </li>
            <li> <?= $this->tag->linkTo('admin/pages', 'Страницы <i class="left material-icons">bookmark_border</i>'); ?></li>
            <li> <?= $this->tag->linkTo('admin/languages', 'Языки <i class="material-icons">language</i>');?></li>
            <li> <?= $this->tag->linkTo('admin/seo', 'Настройки SEO <i class="material-icons">public</i>');?></li>
            <li> <?= $this->tag->linkTo('admin/feedback', 'Отзывы <i class="material-icons">feedback</i>');?></li>
            <li> <?= $this->tag->linkTo('admin/categories', 'Категории <i class="material-icons">toc</i>');?></li>
            <li> <?= $this->tag->linkTo('admin/courses/applications', 'Заявки на курсы <i class="material-icons">receipt</i>') ?></li>
            <li> <?= $this->tag->linkTo('admin/instructors', 'Инструкторы <i class="material-icons">supervisor_account</i>');?></li>
            <li> <?= $this->tag->linkTo('admin/polls', 'Опросы <i class="material-icons">description</i>');?></li>
            <li> <?= $this->tag->linkTo('admin/contacts', 'Контакты <i class="material-icons">settings_phone</i>')?> </li>
            <li> <?= $this->tag->linkTo('admin/support', 'Сообщения <i class="material-icons">message</i>')?> </li>
            <li> <?= $this->tag->linkTo('admin/users', 'Администраторы  <i class="material-icons">info</i>')?> </li>
            <li> <?= $this->tag->linkTo('admin/translate', 'Переводы <i class="material-icons">translate</i>');?></li>
        </ul>

        <ul class="hide-on-med-and-down hide">
            <li> <?= $this->tag->linkTo('admin/news', 'Новости <i class="material-icons">speaker_notes</i>'); ?> </li>
            <li> <?= $this->tag->linkTo('admin/pages', 'Страницы <i class="material-icons ">bookmark_border</i>'); ?></li>
            <li> <?= $this->tag->linkTo('admin/languages', 'Языки <i class="material-icons">language</i>');?></li>
            <li> <?= $this->tag->linkTo('admin/seo', 'Настройки SEO <i class="material-icons">public</i>');?></li>
            <li> <?= $this->tag->linkTo('admin/feedback', 'Отзывы <i class="material-icons">feedback</i>');?></li>
            <li> <?= $this->tag->linkTo('admin/categories', 'Категории <i class="material-icons">toc</i>');?></li>
            <li> <?= $this->tag->linkTo('admin/applications_for_courses', 'Заявки на курсы <i class="material-icons">receipt</i>') ?></li>
            <li> <?= $this->tag->linkTo('admin/instructors', 'Инструкторы <i class="material-icons">supervisor_account</i>');?></li>
            <li> <?= $this->tag->linkTo('admin/pols', 'Опросы <i class="material-icons">description</i>');?></li>
            <li> <?= $this->tag->linkTo('admin/contacts', 'Контакты <i class="material-icons">settings_phone</i>')?> </li>
            <li> <?= $this->tag->linkTo('admin/support', 'Сообщения <i class="material-icons">message</i>')?> </li>
            <li> <?= $this->tag->linkTo('admin/users', 'Администраторы  <i class="material-icons">info</i>')?> </li>
            <li> <?= $this->tag->linkTo('admin/translate', 'Переводы <i class="material-icons">translate</i>');?></li>
        </ul>
    </header>
    <main>
        <div class="admin-page-main-section">
            <?= $this->getContent() ?>
        </div>
    </main>
</body>

</html>