<?php
    use library\Widgets\TopPageNavigationWidget;
    use library\Widgets\MainPageBannerWidget;
    use library\Widgets\FooterContentWidget;
    use library\Widgets\SidebarWidget;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>DeLanaAuto - <?= $this->translate->_('Автошкола в Даугавпилсе') ?></title>

    <meta name="title" content="<?= isset($metaTitle) ? $metaTitle : '' ?>">
    <meta name="description" content="<?= isset($metaDescription) ? $metaDescription : '' ?>">
    <meta name="keywords" content="<?= isset($metaKeywords) ? $metaKeywords : '' ?>">

    <link rel="icon" href="/img/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="/img/favicon.ico" type="image/x-icon">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <?php $this->assets->outputCss() ?>
    <?php $this->assets->outputJs() ?>

</head>

<body>

<?= (new TopPageNavigationWidget())->getWidget(); ?>

<?= (new MainPageBannerWidget())->getWidget(); ?>

<div class="section no-pad-bot">
    <div class="row">
        <div class="col s12 m3 l3" style="border-right: 1px solid lightgrey">
           <?= (new SidebarWidget())->getWidget() ?>
        </div>
        <div class="col s12 m9 l9">
            <?= $this->getContent() ?>
        </div>
    </div>
</div>
    <?= (new FooterContentWidget())->getWidget() ?>
</body>
</html>
