<?php
    use library\Components\TopPageNavigationComponent;
    use library\Components\TopLineComponent;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>DeLanaAuto - Autoskola Daugavpilī</title>

    <link rel="icon" href="img/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <?php $this->assets->outputCss() ?>
    <?php $this->assets->outputJs() ?>

</head>

<body>

<?= (new TopPageNavigationComponent())->getContent(); ?>
<div class="section no-pad-bot main-page-big-container" id="index-banner">
    <div class="container">
        <br><br>
        <div class="row center">
            <a href="#" id="app-for-course" class="btn-large waves-effect waves-light red">Подать заявку</a>
            <a href="#" id="review-button" class="btn-large waves-effect waves-light light-blue">Оставить отзыв</a>
        </div>
        <br><br>
        <div class="row center ">
            <h5 class="header col s12 white-text lighten-2 left arrow_box">
                Запишись прямо сейчас и пройди лучший курс теоретического и практического обучения в автошколе De Lana Auto
            </h5>
        </div>
        <br><br>
    </div>
</div>
<div class="container">
    <?= $this->getContent() ?>
</div>

<footer class="page-footer orange">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <?= (new \library\Components\FooterContactComponent())->getContent(); ?>
            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Settings</h5>
                <ul>
                    <li><a class="white-text" href="#!">Link 1</a></li>
                    <li><a class="white-text" href="#!">Link 2</a></li>
                    <li><a class="white-text" href="#!">Link 3</a></li>
                    <li><a class="white-text" href="#!">Link 4</a></li>
                </ul>
            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Connect</h5>
                <ul>
                    <li><a class="white-text" href="#!">Link 1</a></li>
                    <li><a class="white-text" href="#!">Link 2</a></li>
                    <li><a class="white-text" href="#!">Link 3</a></li>
                    <li><a class="white-text" href="#!">Link 4</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            Made by <a class="orange-text text-lighten-3" href="https://www.facebook.com/Maris.Vigulis">Maris Vigulis</a>
        </div>
    </div>
</footer>
</body>
</html>
