<?php
    use library\Widgets\TopPageNavigationWidget;
    use library\Widgets\MainPageBannerWidget;
    use library\Widgets\FooterContactWidget;
    use library\Widgets\SidebarCategoriesWidget;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>DeLanaAuto - Autoskola Daugavpilī</title>

    <link rel="icon" href="img/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <?php $this->assets->outputCss() ?>
    <?php $this->assets->outputJs() ?>

</head>

<body>

<?= (new TopPageNavigationWidget())->getWidget(); ?>

<?= (new MainPageBannerWidget())->getWidget(); ?>

<div class="section no-pad-bot">
    <div class="row">
        <div class="col s12 m3 l3">
            <?= (new SidebarCategoriesWidget())->getWidget(); ?>
        </div>
        <div class="col s12 m9 l9"  style="border-left: 1px solid lightgrey">
            <div class="row">
                <div class="col s12 m12 l12 center-align">
                    <h5 id="category-title">Новости</h5>
                </div>
            </div>
            <?= $this->getContent() ?>
        </div>
    </div>
</div>


<footer class="page-footer orange">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <?= (new FooterContactWidget())->getWidget(); ?>
            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Settings</h5>
                <ul>
                    <li><a class="white-text" href="#!">Link 1</a></li>
                    <li><a class="white-text" href="#!">Link 2</a></li>
                    <li><a class="white-text" href="#!">Link 3</a></li>
                    <li><a class="white-text" href="#!">Link 4</a></li>
                </ul>
            </div>
            <div class="col l3 s12">
                <h5 class="white-text">Connect</h5>
                <ul>
                    <li><a class="white-text" href="#!">Link 1</a></li>
                    <li><a class="white-text" href="#!">Link 2</a></li>
                    <li><a class="white-text" href="#!">Link 3</a></li>
                    <li><a class="white-text" href="#!">Link 4</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            Made by <a class="orange-text text-lighten-3" href="https://www.facebook.com/Maris.Vigulis">Maris Vigulis</a>
        </div>
    </div>
</footer>
</body>
</html>
